### ISSUE TITLE
Receipt parsing fails due to format changes

### ISSUE THREAD

**Issue by Theome** [Cocoanetics/Kvitto#13]
Since a few days ago, some of the App Receipts that are generated by iOS have a slightly different format and Kvitto fails to parse these receipts properly. In my app, around 50% of the app receipts are affected. I'm already using Kvitto in my app since about a year, but this problem occurred for the first time on September 24. 

It seems that the issue is that sometimes the date format contains fractional seconds, so for example a date looks like this

    2020-09-27T12:07:19.686Z

instead of this:

    2020-09-27T12:07:19Z

The method `_dateFromRFC3339String()` fails to parse the former date string, so `_dateFromData()` throws and `Receipt.init?(contentsOfURL)` returns `nil`.

It's possible that there are some more changes to the format - I'm still investigating. If I find time in the next days, I'll prepare a pull request with a fix.

**Comment by odrobnik** [comment]
Do you have an example receipt? Then We could easily fix that. I'll look into supporting the conversion function with fractional seconds as well.

**Comment by Theome** [comment]
Sure. Can I send you the receipt by email? I don't want to accidentally leak sensitive data.

**Comment by odrobnik** [comment]
> Sure. Can I send you the receipt by email? I don't want to accidentally leak sensitive data.

Of course, oliver@cocoanetics.com

**Comment by odrobnik** [comment]
@Theome I enhanced the date parsing function to work with and without fractional seconds.

**Comment by odrobnik** [comment]
Fix released in [1.0.4](https://www.cocoanetics.com/2020/09/kvitto-1-0-4/)
