### ISSUE TITLE
Check for actualSequence.count == 5 may fail as Apple doesn't always supply 5 elements.

### ISSUE THREAD

**Issue by staninprague** [Cocoanetics/Kvitto#14]
Thank you for the great library! 

Wanted to give you a heads up on the following line of code: 
https://github.com/Cocoanetics/Kvitto/blob/59c95c14bf3859c814df8594b6d5679ab4185b75/Core/Source/PKCS7Container.swift#L48

At some point this year Apple started to supply 3 items in this sequence. I changed it to ```actualSequence.count > 2``` as there is no need to use anything from it above [2]. Since then it is working alright.

This was the issue both in production receipts and sandbox in August 2020. I'm not sure if this issue still persists. But the above change will relax the requirement on the sequence to the data you really need, not stricter.

Thank you again! Looks like Apple is fiddling around with the receipt lately, hope this input will help you and others.

**Comment by odrobnik** [comment]
Thanks @staninprague, I made the suggested change in 
c56e422, I re-tagged the release so that 1.0.4 also contains it.
