### ISSUE TITLE
DateFormatter may cause performance problems and should be reused

### ISSUE THREAD

**Issue by Theome** [Cocoanetics/Kvitto#17]
[This blog post by Sarun](https://sarunw.com/posts/how-expensive-is-dateformatter/) has made me aware of the poor performance of `DateFormatter` if it isn't reused. If these estimations are correct, each call to `_dateFromRFC3339String` in `Functions.swift` can take more than 100ms (initialization of a date formatter plus updating its locale and time zone). 

As an App Store receipt can easily contain dozens of dates, and Kvitto might be used on the main thread (as in the example project), there's a real risk that this performance issue can lead to watchdog terminations.

Initialization and configuration of the `DateFormatter` should be done only once.

**Comment by odrobnik** [comment]
improvement has been merged.
