### ISSUE TITLE
Project is not building with Xcode 12.5 beta 2 (12E5234g)

### ISSUE THREAD

**Issue by MarvinNazari** [Cocoanetics/Kvitto#20]
`DTFoundation` is not building anymore with the new Xcode using SPM. On the other hand it would be nice to make Kvitto dependency free without `DTFoundation`.

<img width="893" alt="Screenshot 2021-02-17 at 09 16 51" src="https://user-images.githubusercontent.com/926772/108175286-e0c6dd80-7100-11eb-81e7-de173db0b7d1.png">

**Comment by Gharib-sara** [comment]
Any update ?
I'm getting the same error

**Comment by odrobnik** [comment]
Fixed it. the correct name of the conditional is `TARGET_OS_IPHONE`.

**Comment by MarvinNazari** [comment]
Thanks for the fix @odrobnik, will you bump the release as well?

**Comment by odrobnik** [comment]
I just released the fix in updates to both DTFoundation and Kvitto.

> dependency free without DTFoundation

It requires the ASN.1 parser in there.
