### ISSUE TITLE
How to Determine Eligibility?

### ISSUE THREAD

**Issue by MacMark** [Cocoanetics/Kvitto#21]
Hi,

i try to determine eligibility for an introductory offer. [Apple's docs say](https://developer.apple.com/documentation/storekit/in-app_purchase/subscriptions_and_offers/implementing_introductory_offers_in_your_app?language=objc):
> In the receipt, check the values of the is_trial_period and the is_in_intro_offer_period for all in-app purchase transactions. If either of these fields are true for a given subscription, the user is not eligible for an introductory offer

I did not find a way to read the `is_trial_period` or the `is_in_intro_offer_period` values from `DTInAppPurchaseReceipt`? Is there a way to access them?

Kind regards,
Markus

**Comment by odrobnik** [comment]
I am not aware that those fields are present in the receipt file, but only on the JSON you get back from querying the server: https://developer.apple.com/documentation/appstorereceipts/is_trial_period

If you can provide me with various receipts that have changes in these flags then I can see if one of the unknown fields is containing those.

**Comment by MacMark** [comment]
Apple doc lists in [In-App Purchase Receipt Fields](https://developer.apple.com/library/archive/releasenotes/General/ValidateAppStoreReceipt/Chapters/ReceiptFields.html#//apple_ref/doc/uid/TP40010573-CH106-SW12) that these fields are available in the `ASN.1 form of the receipt` like here:
![image](https://user-images.githubusercontent.com/626963/118668995-a818cc00-b7f5-11eb-8f51-f6c89ff1c7f8.png)

**Comment by odrobnik** [comment]
In that case it should be easy to add. Would you like to try?

**Comment by MacMark** [comment]
Not sure. Maybe i take a look in my spare time.

**Comment by odrobnik** [comment]
You just add the new fields as properties and then add the decoding to this function: https://github.com/Cocoanetics/Kvitto/blob/develop/Core/Source/InAppPurchaseReceipt.swift#L136 - Bool as Int probably means 0 for false and 1 for true - i.e. _intFromData != 0

**Comment by odrobnik** [comment]
@MacMark I've added the parsing of this field, please test if that works correctly if you have receipts that are within the introductory price period.

**Comment by MacMark** [comment]
Thank you for adding it :-) I will try it out and then come back.

**Comment by MacMark** [comment]
I switched to develop and see the changes on my local copy of the file. I cleaned the build folder and the derived data but somehow the new field is still not visible in Objective-C. The compiler claims 

> Property 'isSubscriptionIntroductoryPricePeriod' not found on object of type 'DTInAppPurchaseReceipt *'

What might i do wrong?
![image](https://user-images.githubusercontent.com/626963/119806927-f3606800-bee2-11eb-972e-126f0a08cacd.png)

**Comment by odrobnik** [comment]
Likely because optional bool values cannot be represented in objc?

**Comment by MacMark** [comment]
Maybe. But the other data like subscriptionExpirationDate are optionals too and they're visible in Objective-C. Could be because of the other data being objects while BOOL is a simple type.

**Comment by odrobnik** [comment]
I made it non-optional. Now you should see it from Objective-C code as well.

**Comment by MacMark** [comment]
Yes, it compiles. Thank you. Now i can go on with testing.

**Comment by MacMark** [comment]
It works for me :-) Thank you!
