### ISSUE TITLE
Question regarding Apple's upcoming migration to SHA-256 signing certificates

### ISSUE THREAD

**Issue by RenGate** [Cocoanetics/Kvitto#24]
Apple will soon start to use the SHA-256 certificates to sign the app receipts. What I would like to ask is will that change create problems for Kvitto's users assuming they don't do local receipt validation and rely on `Receipt(contentsOfURL: ...)` API? 
I've done a bit of testing with iOS 16.6 beta 5 and Xcode 14.3.1 and didn't experience any problems.
Please let me know if you need an example of a new receipt. 
More info about the upcoming change can be found at https://developer.apple.com/documentation/technotes/tn3138-handling-app-store-receipt-signing-certificate-changes

**Comment by odrobnik** [comment]
This change will only affect the signing. Kvitto doesn’t check the signature, I wasn’t able to figure this out. Although I’ve seen some examples where somebody seems to be doing that. So maybe some day somebody puts together the code for it.

But to answer your question, IIRC there’s some validation using a hash, but the signature is being ignored.

**Comment by RenGate** [comment]
Ok, great, thank you for the information.
