### ISSUE TITLE
ld: framework not found DTFoundation for architecture ...

### ISSUE THREAD

**Issue by aalenliang** [Cocoanetics/Kvitto#5]
Using Carthage to build Kvitto, in Cartfile:
`github "Cocoanetics/Kvitto" "develop"`

When build with my iPhone or Generic iOS Device, got the error:
`ld: framework not found DTFoundation for architecture arm64`
sometimes its:
`ld: framework not found DTFoundation for architecture armv7`

When build with Simulators, got the error:
`ld: framework not found DTFoundation for architecture x86_64`

However, the project in Carthage/Checkouts/Kvitto always build success.
I found a related issue in DTFoundation https://github.com/Cocoanetics/DTFoundation/issues/109
It looks like something wrong with the project setting for Carthage usage.

**Comment by aalenliang** [comment]
It seems the solution is copy DTFoundation.framework to Embedded Binaries manually.

**Comment by odrobnik** [comment]
I cannot believe that you need to do something as complicated. `DTFoundation` is a normal git submodule and linked to the `Kvitto` framework. Of course, if you add it to your app, you also need to include the DTFoundation.framework in your Cartfile.

**Comment by aalenliang** [comment]
The issue is because I only include Kvitto in my Cartfile and drag the Kvitto.framework in Carthage/Build to Embedded Binaries, I didn't realize I need to include DTFoundation until meet this compile error.

**Comment by odrobnik** [comment]
@aalenliang so the solution was to also add DTFoundation to the embedded binaries, right?

**Comment by odrobnik** [comment]
@aalenliang ... if this solved the problem please closes both issues on GitHub.
