### ISSUE TITLE
Will Local receipt validation require AppStore authentication?

### ISSUE THREAD

**Issue by ankitkapasi** [Cocoanetics/Kvitto#8]
Hi - I'm interested in using your library for local receipt validation before sending it up to my API. I was wondering though. During the receipt validation flow, will the dreaded IAP authentication modals pop up? I have a requirement to not show those to the user.

**Comment by odrobnik** [comment]
Just for validating you will not trigger the receipt. But if you don't have a valid one you should Refresh it from the App Store - this causes the iTunes login to be prompted.

Usually you get a receipt together with the app when installing from App Store, but in some cases you might have none or an outdated one.

**Comment by ankitkapasi** [comment]
@odrobnik thanks for the clarification.

**Comment by odrobnik** [comment]
There are some bits to the verification that are not in this component, like how to compute and verify the hash of the receipt. If you contact me privately I can provide that to you

**Comment by ankitkapasi** [comment]
@odrobnik just a little confirmation. 

If the user purchases and autorenewing subscription, the first time they open the app after the autorenew is processed by Apple, the app buncle receipt will automatically be updated with the latest IAP receipt from Apple. There is no need for custom code from me and there is no need for user interaction to force a receiptRefresh. 

Is that accurate?

**Comment by odrobnik** [comment]
I am not 100% sure. I believe for the receipt to be automatically refresh when you check it. But there are a few conditions where you need to refresh it. I will email you my SubscriptionManager class to see for yourself.
